title: Guia GAC Brasil
description: Repositório colaborativo com informações a respeito dos veículos da GAC no Brasil.
remote_theme: "mmistakes/minimal-mistakes"
baseurl: "/guia-gac-brasil" 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
