title: Guia GAC Brasil
description: Repositório colaborativo com informações a respeito dos veículos da GAC no Brasil.
baseurl: "/guia-gac-brasil" 
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
